
package com.jyglo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PostXml", targetNamespace = "http://jyglo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostXml {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "show", targetNamespace = "http://jyglo/", className = "com.jyglo.client.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://jyglo/", className = "com.jyglo.client.ShowResponse")
    public String show(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
